name = "sr-prevencion"
main = "worker/dist/index.js"
compatibility_date = "2025-01-01"

[vars]
ENVIRONMENT = "development"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "sr-prevencion-db"
database_id = "a78331db-16a4-4f5c-8133-0e1127069a66"
migrations_dir = "infra/d1/migrations"

# R2 Storage binding
[[r2_buckets]]
binding = "FILESTORE"
bucket_name = "sr-prevencion-files"

[build]
command = "pnpm --filter worker build"

[env.production]
vars = { ENVIRONMENT = "production" }
route = "sr-prev.tu-dominio.cl/*"
# zone_id = "YOUR_ZONE_ID"

[[env.production.d1_databases]]
binding = "DB"
database_name = "sr-prevencion-db-prod"
database_id = "YOUR_PROD_DATABASE_ID"
migrations_dir = "infra/d1/migrations"

[[env.production.r2_buckets]]
binding = "FILESTORE"
bucket_name = "sr-prevencion-files-prod"
