name = "sr-prevencion"
main = "worker/dist/index.js"
compatibility_date = "2025-01-01"

[vars]
ENVIRONMENT = "development"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "sr_d1_db"
database_id = "YOUR_DATABASE_ID"

# R2 Storage binding
[[r2_buckets]]
binding = "FILESTORE"
bucket_name = "sr-preven-files"

[build]
command = "pnpm --filter worker build"

[env.production]
vars = { ENVIRONMENT = "production" }
route = "sr-prev.tu-dominio.cl/*"
# zone_id = "YOUR_ZONE_ID"

[[env.production.d1_databases]]
binding = "DB"
database_name = "sr_d1_db_prod"
database_id = "YOUR_PROD_DATABASE_ID"

[[env.production.r2_buckets]]
binding = "FILESTORE"
bucket_name = "sr-preven-files-prod"
